-- 코드를 입력하세요
SELECT 
    B.AUTHOR_ID
    , A.AUTHOR_NAME
    , B.CATEGORY
    , SUM(B.PRICE * BS.SALES) AS SALES
FROM BOOK B
    LEFT JOIN AUTHOR A
        ON B.AUTHOR_ID = A.AUTHOR_ID
    LEFT JOIN (
        SELECT BOOK_ID, SUM(SALES) AS SALES FROM BOOK_SALES
        WHERE SALES_DATE BETWEEN TO_DATE('2022-01-01','YYYY-MM-DD') 
            AND TO_DATE('2022-01-31','YYYY-MM-DD')
        GROUP BY BOOK_ID
    )BS
        ON B.BOOK_ID = BS.BOOK_ID
GROUP BY B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY
ORDER BY B.AUTHOR_ID, B.CATEGORY DESC

