-- 코드를 입력하세요
-- 1) 자동차 종류가 '세단' 또는 'SUV' 인 자동차 중
-- 2) 2022년 11월 1일부터 2022년 11월 30일까지 대여 가능 차
-- 3) 30일간의 대여 금액이 50만원 이상 200만원 미만인 자동차
SELECT 
     CAR_ID
    , CAR_TYPE
    , ROUND(DAILY_FEE * (100-DISCOUNT_RATE) * 0.01 * 30,0) AS FEE
FROM (
 SELECT 
         C.CAR_ID
        , C.CAR_TYPE
        , C.DAILY_FEE
        , P.DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_CAR C
        LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P 
            ON C.CAR_TYPE = P.CAR_TYPE 
            AND P.DURATION_TYPE = '30일 이상'
    WHERE C.CAR_TYPE IN ('세단','SUV')
    GROUP BY C.CAR_ID, C.CAR_TYPE, C.DAILY_FEE, P.DISCOUNT_RATE
) A
WHERE DAILY_FEE * (100-DISCOUNT_RATE) * 0.01 * 30 >= 500000
AND DAILY_FEE * (100-DISCOUNT_RATE) * 0.01 * 30 < 2000000
AND CAR_ID NOT IN(
    SELECT DISTINCT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE < TO_DATE('20221101','YYYYMMDD') 
    AND END_DATE > TO_DATE('20221101','YYYYMMDD')
)
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC


