-- 코드를 입력하세요
SELECT T2.FOOD_TYPE,T2.REST_ID,T2.REST_NAME,T2.FAVORITES
FROM (SELECT FOOD_TYPE, MAX(FAVORITES) FAVORITES
      FROM REST_INFO
      GROUP BY FOOD_TYPE
 ) T1 
LEFT JOIN REST_INFO T2 
ON T1.FOOD_TYPE = T2.FOOD_TYPE
AND T1.FAVORITES = T2.FAVORITES
ORDER BY T1.FOOD_TYPE DESC;