-- 코드를 입력하세요
-- SELECT
--      USER_ID	
--     , NICKNAME	
--     , CITY || STREET_ADDRESS1 || STREET_ADDRESS2 AS "전체주소"
--     , SUBSTR(TLNO,0,3)  || '-' || SUBSTR(TLNO,3,4)  || '-' || SUBSTR(TLNO,-1,4)  AS "전화번호"
-- FROM USED_GOODS_USER U 
--     INNER JOIN USED_GOODS_BOARD B 
--         ON U.USER_ID = B.WRITER_ID
-- GROUP BY U.USER_ID, NICKNAME HAVING COUNT(U.USER_ID)>=3
-- ORDER BY U.USER_ID DESC
-- 위의 코드는 GROUP BY 에 SELECT 된 모든 컬럼을 넣지 않아서 안됨.

SELECT
     USER_ID	
    , NICKNAME	
    , CITY || ' ' || STREET_ADDRESS1 || ' ' || STREET_ADDRESS2 AS "전체주소"
    , SUBSTR(TLNO,0,3)  || '-' || SUBSTR(TLNO,4,4)  || '-' || SUBSTR(TLNO,-4,4)  AS "전화번호"
FROM USED_GOODS_USER U 
WHERE USER_ID IN(
    SELECT WRITER_ID FROM USED_GOODS_BOARD
    GROUP BY WRITER_ID HAVING COUNT(*)>=3
)
ORDER BY U.USER_ID DESC