-- 코드를 입력하세요
SELECT 
    RI.REST_ID
    , RI.REST_NAME
    ,  RI.FOOD_TYPE
    ,  RI.FAVORITES
    ,  RI.ADDRESS
    , ROUND(AVG(RR.REVIEW_SCORE), 2) AS SCORE
FROM (
    SELECT
        REST_ID
        , REST_NAME
        , FOOD_TYPE
        , FAVORITES
        , ADDRESS
    FROM REST_INFO
    WHERE ADDRESS LIKE '서울%'
) RI
INNER JOIN REST_REVIEW RR ON RI.REST_ID = RR.REST_ID
GROUP BY RI.REST_ID,RI.REST_NAME,RI.FOOD_TYPE,RI.FAVORITES,RI.ADDRESS
ORDER BY AVG(RR.REVIEW_SCORE) DESC, FAVORITES DESC