-- 코드를 입력하세요
SELECT 
    YEAR
    , MONTH
    , GENDER
    , COUNT(USERS) AS USERS
FROM (
    SELECT
        DISTINCT TO_CHAR(SALES_DATE, 'YYYY') AS YEAR
        , TO_NUMBER(TO_CHAR(SALES_DATE,'MM')) AS MONTH
        , GENDER AS GENDER
        , U.USER_ID AS USERS
    FROM ONLINE_SALE O
        LEFT JOIN USER_INFO U 
            ON O.USER_ID = U.USER_ID
    WHERE U.GENDER IS NOT NULL
)
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER