-- 코드를 입력하세요
-- 1) T2에서 대여중인 CAR_ID 목록 구함
-- 2) JOIN 된 테이블에서 CAR_ID가 없다면, 대여 가능.
SELECT 
    DISTINCT T1.CAR_ID,
    CASE WHEN T2.CAR_ID IS NULL THEN '대여 가능' ELSE '대여중' END AS " AVAILABILITY"
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY T1
LEFT JOIN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE <= TO_DATE('2022-10-16','YYYY-MM-DD')
    AND END_DATE >= TO_DATE('2022-10-16','YYYY-MM-DD')
    GROUP BY CAR_ID
    ORDER BY CAR_ID DESC 
)T2
ON T1.CAR_ID = T2.CAR_ID
ORDER BY T1.CAR_ID DESC

