-- 코드를 입력하세요
SELECT
    FP.PRODUCT_ID
    , FP.PRODUCT_NAME
    , (FP.PRICE * FO.AMOUNT) AS TOTAL_SALES
FROM  (
        SELECT PRODUCT_ID, NVL(SUM(AMOUNT),0) AS AMOUNT
        FROM FOOD_ORDER
        WHERE PRODUCE_DATE BETWEEN TO_DATE('20220501','YYYYMMDD') 
            AND TO_DATE('20220531','YYYYMMDD')
        GROUP BY PRODUCT_ID 
)FO
LEFT JOIN FOOD_PRODUCT FP
    ON FP.PRODUCT_ID =  FO.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, FP.PRODUCT_ID ASC
