-- 코드를 입력하세요
SELECT FLAVOR
FROM (
    SELECT
         F.FLAVOR
        , F.TOTAL_ORDER + J.TOTAL_ORDER AS TOTAL_ORDER
    FROM FIRST_HALF F
    LEFT JOIN (
        SELECT 
            FLAVOR
            , SUM(TOTAL_ORDER) AS TOTAL_ORDER
        FROM JULY 
        GROUP BY FLAVOR
    ) J
    ON F.FLAVOR = J.FLAVOR
    ORDER BY TOTAL_ORDER DESC
    FETCH FIRST 3 ROW ONLY
)