-- 코드를 입력하세요
SELECT
    A.APNT_NO
    , P.PT_NAME
    , P.PT_NO
    , D.MCDP_CD
    , D.DR_NAME
    , A.APNT_YMD
FROM APPOINTMENT A
    LEFT JOIN DOCTOR D ON A.MDDR_ID = D.DR_ID
    LEFT JOIN PATIENT P ON A.PT_NO = P.PT_NO
WHERE A.APNT_YMD BETWEEN TO_DATE('2022-04-13 00:00:00', 'YYYY-MM-DD HH24:MI:SS')
                 AND TO_DATE('2022-04-13 23:59:59', 'YYYY-MM-DD HH24:MI:SS')
AND A.APNT_CNCL_YN ='N'
AND A.MCDP_CD='CS'
ORDER BY A.APNT_YMD