-- 코드를 입력하세요
-- HOUR 출력예시에 한자리수 시간은 0 제외--> TO_NUMBER 처리
SELECT
      TO_NUMBER(TO_CHAR(DATETIME,'HH24')) AS HOUR
    , COUNT(*)
FROM ANIMAL_OUTS 
WHERE TO_CHAR(DATETIME,'HH24') BETWEEN '09' AND '19'
GROUP BY TO_CHAR(DATETIME, 'HH24')
ORDER BY TO_CHAR(DATETIME, 'HH24') ASC