-- 코드를 입력하세요

SELECT 
      TO_NUMBER(TO_CHAR(START_DATE,'MM')) AS MONTH
     , CAR_ID
     , COUNT(HISTORY_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    WHERE TO_CHAR(START_DATE,'YYYYMM') BETWEEN '202208' AND '202210'
    GROUP BY CAR_ID HAVING COUNT(*)>=5
)
AND TO_CHAR(START_DATE,'YYYYMM') BETWEEN '202208' AND '202210'
GROUP BY TO_CHAR(START_DATE,'MM') ,CAR_ID HAVING COUNT(*) > 0
ORDER BY TO_CHAR(START_DATE,'MM') ,CAR_ID DESC