-- 코드를 입력하세요
SELECT
    II.FLAVOR AS FLAVOR
FROM FIRST_HALF FH
    INNER JOIN ICECREAM_INFO II ON FH.FLAVOR = II.FLAVOR
WHERE FH.TOTAL_ORDER > 3000 AND INGREDIENT_TYPE ='fruit_based'
ORDER BY FH.TOTAL_ORDER DESC