-- 코드를 입력하세요
SELECT DISTINCT H.CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C
    INNER JOIN CAR_RENTAL_COMPANY_CAR H ON C.CAR_ID = H.CAR_ID
WHERE CAR_TYPE = '세단' AND TO_CHAR(START_DATE,'MM') = '10'
ORDER BY H.CAR_ID DESC
