-- 코드를 입력하세요
SELECT 
BO.TITLE
,BO.BOARD_ID
,RE.REPLY_ID
,RE.WRITER_ID
,RE.CONTENTS
,TO_CHAR(RE.CREATED_DATE,'YYYY-MM-DD') AS "CREATED_DATE"
FROM  USED_GOODS_BOARD BO
    INNER JOIN USED_GOODS_REPLY RE
        ON BO.BOARD_ID = RE.BOARD_ID
WHERE BO.CREATED_DATE >= TO_DATE('2022-10-01','YYYY-MM-DD') 
AND BO.CREATED_DATE <= TO_DATE('2022-10-31','YYYY-MM-DD')
ORDER BY RE.CREATED_DATE ASC, BO.TITLE ASC;

