-- 코드를 입력하세요
SELECT
    A.CATEGORY
    , A.PRICE AS MAX_PRICE
    , A.PRODUCT_NAME
FROM
    (
    SELECT
        CATEGORY
        ,MAX(PRICE) AS PRICE
    FROM FOOD_PRODUCT
    WHERE
        CATEGORY IN ('과자', '식용유', '국', '김치')
    GROUP BY
        CATEGORY
) B
LEFT JOIN FOOD_PRODUCT A
    ON A.CATEGORY = B.CATEGORY
    AND A.PRICE = B.PRICE
ORDER BY
    MAX_PRICE DESC